/**
 * OWASP ASVS 4.0.3, as identifiers.
 *
 * GENERATED by scripts/build-asvs.mjs. Do not edit by hand; edit the mapping
 * in that script and regenerate.
 *
 * Requirement text is NOT here. ASVS is published under CC BY-SA 4.0, and this
 * file carries only identifiers, CWE references and verification levels, with
 * a link out to the published standard for the wording. Attribution:
 * OWASP Application Security Verification Standard 4.0.3, CC BY-SA 4.0.
 * https://owasp.org/www-project-application-security-verification-standard/
 *
 * 286 requirements. 21 of them can be reached by
 * something this engine tests for -- which is the number that matters, and the
 * reason the product says how many it did not test rather than reporting a
 * percentage over the ones it did.
 */

export const ASVS_VERSION = "4.0.3";
export const ASVS_LICENCE = "CC BY-SA 4.0";
export const ASVS_HOME = "https://owasp.org/www-project-application-security-verification-standard/";

export interface AsvsRequirement {
  id: string;
  chapter: string;
  section: string;
  /** The CWE the standard associates with this requirement, where it names one. */
  cwe: number | null;
  l1: boolean;
  l2: boolean;
  l3: boolean;
}

export interface FindingMapping {
  requirements: string[];
  /** How the pairing was located in the standard, so a reviewer can repeat it. */
  why: string;
  /** True when the standard has no requirement for this and the nearest was taken. */
  approximate?: boolean;
}

export const ASVS_CATALOGUE: AsvsRequirement[] = [
  {
    "id": "V1.1.1",
    "chapter": "V1",
    "section": "V1.1",
    "cwe": null,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.1.2",
    "chapter": "V1",
    "section": "V1.1",
    "cwe": 1053,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.1.3",
    "chapter": "V1",
    "section": "V1.1",
    "cwe": 1110,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.1.4",
    "chapter": "V1",
    "section": "V1.1",
    "cwe": 1059,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.1.5",
    "chapter": "V1",
    "section": "V1.1",
    "cwe": 1059,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.1.6",
    "chapter": "V1",
    "section": "V1.1",
    "cwe": 637,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.1.7",
    "chapter": "V1",
    "section": "V1.1",
    "cwe": 637,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.2.1",
    "chapter": "V1",
    "section": "V1.2",
    "cwe": 250,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.2.2",
    "chapter": "V1",
    "section": "V1.2",
    "cwe": 306,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.2.3",
    "chapter": "V1",
    "section": "V1.2",
    "cwe": 306,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.2.4",
    "chapter": "V1",
    "section": "V1.2",
    "cwe": 306,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.4.1",
    "chapter": "V1",
    "section": "V1.4",
    "cwe": 602,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.4.2",
    "chapter": "V1",
    "section": "V1.4",
    "cwe": null,
    "l1": false,
    "l2": false,
    "l3": false
  },
  {
    "id": "V1.4.3",
    "chapter": "V1",
    "section": "V1.4",
    "cwe": null,
    "l1": false,
    "l2": false,
    "l3": false
  },
  {
    "id": "V1.4.4",
    "chapter": "V1",
    "section": "V1.4",
    "cwe": 284,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.4.5",
    "chapter": "V1",
    "section": "V1.4",
    "cwe": 275,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.5.1",
    "chapter": "V1",
    "section": "V1.5",
    "cwe": 1029,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.5.2",
    "chapter": "V1",
    "section": "V1.5",
    "cwe": 502,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.5.3",
    "chapter": "V1",
    "section": "V1.5",
    "cwe": 602,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.5.4",
    "chapter": "V1",
    "section": "V1.5",
    "cwe": 116,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.6.1",
    "chapter": "V1",
    "section": "V1.6",
    "cwe": 320,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.6.2",
    "chapter": "V1",
    "section": "V1.6",
    "cwe": 320,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.6.3",
    "chapter": "V1",
    "section": "V1.6",
    "cwe": 320,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.6.4",
    "chapter": "V1",
    "section": "V1.6",
    "cwe": 320,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.7.1",
    "chapter": "V1",
    "section": "V1.7",
    "cwe": 1009,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.7.2",
    "chapter": "V1",
    "section": "V1.7",
    "cwe": null,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.8.1",
    "chapter": "V1",
    "section": "V1.8",
    "cwe": null,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.8.2",
    "chapter": "V1",
    "section": "V1.8",
    "cwe": null,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.9.1",
    "chapter": "V1",
    "section": "V1.9",
    "cwe": 319,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.9.2",
    "chapter": "V1",
    "section": "V1.9",
    "cwe": 295,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.10.1",
    "chapter": "V1",
    "section": "V1.10",
    "cwe": 284,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.11.1",
    "chapter": "V1",
    "section": "V1.11",
    "cwe": 1059,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.11.2",
    "chapter": "V1",
    "section": "V1.11",
    "cwe": 362,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.11.3",
    "chapter": "V1",
    "section": "V1.11",
    "cwe": 367,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V1.12.1",
    "chapter": "V1",
    "section": "V1.12",
    "cwe": null,
    "l1": false,
    "l2": false,
    "l3": false
  },
  {
    "id": "V1.12.2",
    "chapter": "V1",
    "section": "V1.12",
    "cwe": 646,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.14.1",
    "chapter": "V1",
    "section": "V1.14",
    "cwe": 923,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.14.2",
    "chapter": "V1",
    "section": "V1.14",
    "cwe": 494,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.14.3",
    "chapter": "V1",
    "section": "V1.14",
    "cwe": 1104,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.14.4",
    "chapter": "V1",
    "section": "V1.14",
    "cwe": null,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.14.5",
    "chapter": "V1",
    "section": "V1.14",
    "cwe": 265,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V1.14.6",
    "chapter": "V1",
    "section": "V1.14",
    "cwe": 477,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.1.1",
    "chapter": "V2",
    "section": "V2.1",
    "cwe": 521,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.1.2",
    "chapter": "V2",
    "section": "V2.1",
    "cwe": 521,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.1.3",
    "chapter": "V2",
    "section": "V2.1",
    "cwe": 521,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.1.4",
    "chapter": "V2",
    "section": "V2.1",
    "cwe": 521,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.1.5",
    "chapter": "V2",
    "section": "V2.1",
    "cwe": 620,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.1.6",
    "chapter": "V2",
    "section": "V2.1",
    "cwe": 620,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.1.7",
    "chapter": "V2",
    "section": "V2.1",
    "cwe": 521,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.1.8",
    "chapter": "V2",
    "section": "V2.1",
    "cwe": 521,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.1.9",
    "chapter": "V2",
    "section": "V2.1",
    "cwe": 521,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.1.10",
    "chapter": "V2",
    "section": "V2.1",
    "cwe": 263,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.1.11",
    "chapter": "V2",
    "section": "V2.1",
    "cwe": 521,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.1.12",
    "chapter": "V2",
    "section": "V2.1",
    "cwe": 521,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.2.1",
    "chapter": "V2",
    "section": "V2.2",
    "cwe": 307,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.2.2",
    "chapter": "V2",
    "section": "V2.2",
    "cwe": 304,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.2.3",
    "chapter": "V2",
    "section": "V2.2",
    "cwe": 620,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.2.4",
    "chapter": "V2",
    "section": "V2.2",
    "cwe": 308,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V2.2.5",
    "chapter": "V2",
    "section": "V2.2",
    "cwe": 319,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V2.2.6",
    "chapter": "V2",
    "section": "V2.2",
    "cwe": 308,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V2.2.7",
    "chapter": "V2",
    "section": "V2.2",
    "cwe": 308,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V2.3.1",
    "chapter": "V2",
    "section": "V2.3",
    "cwe": 330,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.3.2",
    "chapter": "V2",
    "section": "V2.3",
    "cwe": 308,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.3.3",
    "chapter": "V2",
    "section": "V2.3",
    "cwe": 287,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.4.1",
    "chapter": "V2",
    "section": "V2.4",
    "cwe": 916,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.4.2",
    "chapter": "V2",
    "section": "V2.4",
    "cwe": 916,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.4.3",
    "chapter": "V2",
    "section": "V2.4",
    "cwe": 916,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.4.4",
    "chapter": "V2",
    "section": "V2.4",
    "cwe": 916,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.4.5",
    "chapter": "V2",
    "section": "V2.4",
    "cwe": 916,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.5.1",
    "chapter": "V2",
    "section": "V2.5",
    "cwe": 640,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.5.2",
    "chapter": "V2",
    "section": "V2.5",
    "cwe": 640,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.5.3",
    "chapter": "V2",
    "section": "V2.5",
    "cwe": 640,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.5.4",
    "chapter": "V2",
    "section": "V2.5",
    "cwe": 16,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.5.5",
    "chapter": "V2",
    "section": "V2.5",
    "cwe": 304,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.5.6",
    "chapter": "V2",
    "section": "V2.5",
    "cwe": 640,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.5.7",
    "chapter": "V2",
    "section": "V2.5",
    "cwe": 308,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.6.1",
    "chapter": "V2",
    "section": "V2.6",
    "cwe": 308,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.6.2",
    "chapter": "V2",
    "section": "V2.6",
    "cwe": 330,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.6.3",
    "chapter": "V2",
    "section": "V2.6",
    "cwe": 310,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.7.1",
    "chapter": "V2",
    "section": "V2.7",
    "cwe": 287,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.7.2",
    "chapter": "V2",
    "section": "V2.7",
    "cwe": 287,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.7.3",
    "chapter": "V2",
    "section": "V2.7",
    "cwe": 287,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.7.4",
    "chapter": "V2",
    "section": "V2.7",
    "cwe": 523,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.7.5",
    "chapter": "V2",
    "section": "V2.7",
    "cwe": 256,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.7.6",
    "chapter": "V2",
    "section": "V2.7",
    "cwe": 310,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.8.1",
    "chapter": "V2",
    "section": "V2.8",
    "cwe": 613,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.8.2",
    "chapter": "V2",
    "section": "V2.8",
    "cwe": 320,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.8.3",
    "chapter": "V2",
    "section": "V2.8",
    "cwe": 326,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.8.4",
    "chapter": "V2",
    "section": "V2.8",
    "cwe": 287,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.8.5",
    "chapter": "V2",
    "section": "V2.8",
    "cwe": 287,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.8.6",
    "chapter": "V2",
    "section": "V2.8",
    "cwe": 613,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.8.7",
    "chapter": "V2",
    "section": "V2.8",
    "cwe": 308,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.9.1",
    "chapter": "V2",
    "section": "V2.9",
    "cwe": 320,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.9.2",
    "chapter": "V2",
    "section": "V2.9",
    "cwe": 330,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.9.3",
    "chapter": "V2",
    "section": "V2.9",
    "cwe": 327,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.10.1",
    "chapter": "V2",
    "section": "V2.10",
    "cwe": 287,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.10.2",
    "chapter": "V2",
    "section": "V2.10",
    "cwe": 255,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.10.3",
    "chapter": "V2",
    "section": "V2.10",
    "cwe": 522,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V2.10.4",
    "chapter": "V2",
    "section": "V2.10",
    "cwe": 798,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.1.1",
    "chapter": "V3",
    "section": "V3.1",
    "cwe": 598,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.2.1",
    "chapter": "V3",
    "section": "V3.2",
    "cwe": 384,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.2.2",
    "chapter": "V3",
    "section": "V3.2",
    "cwe": 331,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.2.3",
    "chapter": "V3",
    "section": "V3.2",
    "cwe": 539,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.2.4",
    "chapter": "V3",
    "section": "V3.2",
    "cwe": 331,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.3.1",
    "chapter": "V3",
    "section": "V3.3",
    "cwe": 613,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.3.2",
    "chapter": "V3",
    "section": "V3.3",
    "cwe": 613,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.3.3",
    "chapter": "V3",
    "section": "V3.3",
    "cwe": 613,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.3.4",
    "chapter": "V3",
    "section": "V3.3",
    "cwe": 613,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.4.1",
    "chapter": "V3",
    "section": "V3.4",
    "cwe": 614,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.4.2",
    "chapter": "V3",
    "section": "V3.4",
    "cwe": 1004,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.4.3",
    "chapter": "V3",
    "section": "V3.4",
    "cwe": 1275,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.4.4",
    "chapter": "V3",
    "section": "V3.4",
    "cwe": 16,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.4.5",
    "chapter": "V3",
    "section": "V3.4",
    "cwe": 16,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.5.1",
    "chapter": "V3",
    "section": "V3.5",
    "cwe": 290,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.5.2",
    "chapter": "V3",
    "section": "V3.5",
    "cwe": 798,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.5.3",
    "chapter": "V3",
    "section": "V3.5",
    "cwe": 345,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V3.6.1",
    "chapter": "V3",
    "section": "V3.6",
    "cwe": 613,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V3.6.2",
    "chapter": "V3",
    "section": "V3.6",
    "cwe": 613,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V3.7.1",
    "chapter": "V3",
    "section": "V3.7",
    "cwe": 306,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V4.1.1",
    "chapter": "V4",
    "section": "V4.1",
    "cwe": 602,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V4.1.2",
    "chapter": "V4",
    "section": "V4.1",
    "cwe": 639,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V4.1.3",
    "chapter": "V4",
    "section": "V4.1",
    "cwe": 285,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V4.1.4",
    "chapter": "V4",
    "section": "V4.1",
    "cwe": null,
    "l1": false,
    "l2": false,
    "l3": false
  },
  {
    "id": "V4.1.5",
    "chapter": "V4",
    "section": "V4.1",
    "cwe": 285,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V4.2.1",
    "chapter": "V4",
    "section": "V4.2",
    "cwe": 639,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V4.2.2",
    "chapter": "V4",
    "section": "V4.2",
    "cwe": 352,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V4.3.1",
    "chapter": "V4",
    "section": "V4.3",
    "cwe": 419,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V4.3.2",
    "chapter": "V4",
    "section": "V4.3",
    "cwe": 548,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V4.3.3",
    "chapter": "V4",
    "section": "V4.3",
    "cwe": 732,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.1.1",
    "chapter": "V5",
    "section": "V5.1",
    "cwe": 235,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.1.2",
    "chapter": "V5",
    "section": "V5.1",
    "cwe": 915,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.1.3",
    "chapter": "V5",
    "section": "V5.1",
    "cwe": 20,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.1.4",
    "chapter": "V5",
    "section": "V5.1",
    "cwe": 20,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.1.5",
    "chapter": "V5",
    "section": "V5.1",
    "cwe": 601,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.2.1",
    "chapter": "V5",
    "section": "V5.2",
    "cwe": 116,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.2.2",
    "chapter": "V5",
    "section": "V5.2",
    "cwe": 138,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.2.3",
    "chapter": "V5",
    "section": "V5.2",
    "cwe": 147,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.2.4",
    "chapter": "V5",
    "section": "V5.2",
    "cwe": 95,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.2.5",
    "chapter": "V5",
    "section": "V5.2",
    "cwe": 94,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.2.6",
    "chapter": "V5",
    "section": "V5.2",
    "cwe": 918,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.2.7",
    "chapter": "V5",
    "section": "V5.2",
    "cwe": 159,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.2.8",
    "chapter": "V5",
    "section": "V5.2",
    "cwe": 94,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.3.1",
    "chapter": "V5",
    "section": "V5.3",
    "cwe": 116,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.3.2",
    "chapter": "V5",
    "section": "V5.3",
    "cwe": 176,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.3.3",
    "chapter": "V5",
    "section": "V5.3",
    "cwe": 79,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.3.4",
    "chapter": "V5",
    "section": "V5.3",
    "cwe": 89,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.3.5",
    "chapter": "V5",
    "section": "V5.3",
    "cwe": 89,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.3.6",
    "chapter": "V5",
    "section": "V5.3",
    "cwe": 830,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.3.7",
    "chapter": "V5",
    "section": "V5.3",
    "cwe": 90,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.3.8",
    "chapter": "V5",
    "section": "V5.3",
    "cwe": 78,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.3.9",
    "chapter": "V5",
    "section": "V5.3",
    "cwe": 829,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.3.10",
    "chapter": "V5",
    "section": "V5.3",
    "cwe": 643,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.4.1",
    "chapter": "V5",
    "section": "V5.4",
    "cwe": 120,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.4.2",
    "chapter": "V5",
    "section": "V5.4",
    "cwe": 134,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.4.3",
    "chapter": "V5",
    "section": "V5.4",
    "cwe": 190,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.5.1",
    "chapter": "V5",
    "section": "V5.5",
    "cwe": 502,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.5.2",
    "chapter": "V5",
    "section": "V5.5",
    "cwe": 611,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.5.3",
    "chapter": "V5",
    "section": "V5.5",
    "cwe": 502,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V5.5.4",
    "chapter": "V5",
    "section": "V5.5",
    "cwe": 95,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V6.1.1",
    "chapter": "V6",
    "section": "V6.1",
    "cwe": 311,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V6.1.2",
    "chapter": "V6",
    "section": "V6.1",
    "cwe": 311,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V6.1.3",
    "chapter": "V6",
    "section": "V6.1",
    "cwe": 311,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V6.2.1",
    "chapter": "V6",
    "section": "V6.2",
    "cwe": 310,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V6.2.2",
    "chapter": "V6",
    "section": "V6.2",
    "cwe": 327,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V6.2.3",
    "chapter": "V6",
    "section": "V6.2",
    "cwe": 326,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V6.2.4",
    "chapter": "V6",
    "section": "V6.2",
    "cwe": 326,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V6.2.5",
    "chapter": "V6",
    "section": "V6.2",
    "cwe": 326,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V6.2.6",
    "chapter": "V6",
    "section": "V6.2",
    "cwe": 326,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V6.2.7",
    "chapter": "V6",
    "section": "V6.2",
    "cwe": 326,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V6.2.8",
    "chapter": "V6",
    "section": "V6.2",
    "cwe": 385,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V6.3.1",
    "chapter": "V6",
    "section": "V6.3",
    "cwe": 338,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V6.3.2",
    "chapter": "V6",
    "section": "V6.3",
    "cwe": 338,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V6.3.3",
    "chapter": "V6",
    "section": "V6.3",
    "cwe": 338,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V6.4.1",
    "chapter": "V6",
    "section": "V6.4",
    "cwe": 798,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V6.4.2",
    "chapter": "V6",
    "section": "V6.4",
    "cwe": 320,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V7.1.1",
    "chapter": "V7",
    "section": "V7.1",
    "cwe": 532,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V7.1.2",
    "chapter": "V7",
    "section": "V7.1",
    "cwe": 532,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V7.1.3",
    "chapter": "V7",
    "section": "V7.1",
    "cwe": 778,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V7.1.4",
    "chapter": "V7",
    "section": "V7.1",
    "cwe": 778,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V7.2.1",
    "chapter": "V7",
    "section": "V7.2",
    "cwe": 778,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V7.2.2",
    "chapter": "V7",
    "section": "V7.2",
    "cwe": 285,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V7.3.1",
    "chapter": "V7",
    "section": "V7.3",
    "cwe": 117,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V7.3.2",
    "chapter": "V7",
    "section": "V7.3",
    "cwe": null,
    "l1": false,
    "l2": false,
    "l3": false
  },
  {
    "id": "V7.3.3",
    "chapter": "V7",
    "section": "V7.3",
    "cwe": 200,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V7.3.4",
    "chapter": "V7",
    "section": "V7.3",
    "cwe": null,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V7.4.1",
    "chapter": "V7",
    "section": "V7.4",
    "cwe": 210,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V7.4.2",
    "chapter": "V7",
    "section": "V7.4",
    "cwe": 544,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V7.4.3",
    "chapter": "V7",
    "section": "V7.4",
    "cwe": 431,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.1.1",
    "chapter": "V8",
    "section": "V8.1",
    "cwe": 524,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.1.2",
    "chapter": "V8",
    "section": "V8.1",
    "cwe": 524,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.1.3",
    "chapter": "V8",
    "section": "V8.1",
    "cwe": 233,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.1.4",
    "chapter": "V8",
    "section": "V8.1",
    "cwe": 770,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.1.5",
    "chapter": "V8",
    "section": "V8.1",
    "cwe": 19,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V8.1.6",
    "chapter": "V8",
    "section": "V8.1",
    "cwe": 19,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V8.2.1",
    "chapter": "V8",
    "section": "V8.2",
    "cwe": 525,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.2.2",
    "chapter": "V8",
    "section": "V8.2",
    "cwe": 922,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.2.3",
    "chapter": "V8",
    "section": "V8.2",
    "cwe": 922,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.3.1",
    "chapter": "V8",
    "section": "V8.3",
    "cwe": 319,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.3.2",
    "chapter": "V8",
    "section": "V8.3",
    "cwe": 212,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.3.3",
    "chapter": "V8",
    "section": "V8.3",
    "cwe": 285,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.3.4",
    "chapter": "V8",
    "section": "V8.3",
    "cwe": 200,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.3.5",
    "chapter": "V8",
    "section": "V8.3",
    "cwe": 532,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.3.6",
    "chapter": "V8",
    "section": "V8.3",
    "cwe": 226,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.3.7",
    "chapter": "V8",
    "section": "V8.3",
    "cwe": 327,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V8.3.8",
    "chapter": "V8",
    "section": "V8.3",
    "cwe": 285,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V9.1.1",
    "chapter": "V9",
    "section": "V9.1",
    "cwe": 319,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V9.1.2",
    "chapter": "V9",
    "section": "V9.1",
    "cwe": 326,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V9.1.3",
    "chapter": "V9",
    "section": "V9.1",
    "cwe": 326,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V9.2.1",
    "chapter": "V9",
    "section": "V9.2",
    "cwe": 295,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V9.2.2",
    "chapter": "V9",
    "section": "V9.2",
    "cwe": 319,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V9.2.3",
    "chapter": "V9",
    "section": "V9.2",
    "cwe": 287,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V9.2.4",
    "chapter": "V9",
    "section": "V9.2",
    "cwe": 299,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V9.2.5",
    "chapter": "V9",
    "section": "V9.2",
    "cwe": 544,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V10.1.1",
    "chapter": "V10",
    "section": "V10.1",
    "cwe": 749,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V10.2.1",
    "chapter": "V10",
    "section": "V10.2",
    "cwe": 359,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V10.2.2",
    "chapter": "V10",
    "section": "V10.2",
    "cwe": 272,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V10.2.3",
    "chapter": "V10",
    "section": "V10.2",
    "cwe": 507,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V10.2.4",
    "chapter": "V10",
    "section": "V10.2",
    "cwe": 511,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V10.2.5",
    "chapter": "V10",
    "section": "V10.2",
    "cwe": 511,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V10.2.6",
    "chapter": "V10",
    "section": "V10.2",
    "cwe": 507,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V10.3.1",
    "chapter": "V10",
    "section": "V10.3",
    "cwe": 16,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V10.3.2",
    "chapter": "V10",
    "section": "V10.3",
    "cwe": 353,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V10.3.3",
    "chapter": "V10",
    "section": "V10.3",
    "cwe": 350,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V11.1.1",
    "chapter": "V11",
    "section": "V11.1",
    "cwe": 841,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V11.1.2",
    "chapter": "V11",
    "section": "V11.1",
    "cwe": 799,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V11.1.3",
    "chapter": "V11",
    "section": "V11.1",
    "cwe": 770,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V11.1.4",
    "chapter": "V11",
    "section": "V11.1",
    "cwe": 770,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V11.1.5",
    "chapter": "V11",
    "section": "V11.1",
    "cwe": 841,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V11.1.6",
    "chapter": "V11",
    "section": "V11.1",
    "cwe": 367,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V11.1.7",
    "chapter": "V11",
    "section": "V11.1",
    "cwe": 754,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V11.1.8",
    "chapter": "V11",
    "section": "V11.1",
    "cwe": 390,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.1.1",
    "chapter": "V12",
    "section": "V12.1",
    "cwe": 400,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.1.2",
    "chapter": "V12",
    "section": "V12.1",
    "cwe": 409,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.1.3",
    "chapter": "V12",
    "section": "V12.1",
    "cwe": 770,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.2.1",
    "chapter": "V12",
    "section": "V12.2",
    "cwe": 434,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.3.1",
    "chapter": "V12",
    "section": "V12.3",
    "cwe": 22,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.3.2",
    "chapter": "V12",
    "section": "V12.3",
    "cwe": 73,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.3.3",
    "chapter": "V12",
    "section": "V12.3",
    "cwe": 98,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.3.4",
    "chapter": "V12",
    "section": "V12.3",
    "cwe": 641,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.3.5",
    "chapter": "V12",
    "section": "V12.3",
    "cwe": 78,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.3.6",
    "chapter": "V12",
    "section": "V12.3",
    "cwe": 829,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.4.1",
    "chapter": "V12",
    "section": "V12.4",
    "cwe": 552,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.4.2",
    "chapter": "V12",
    "section": "V12.4",
    "cwe": 509,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.5.1",
    "chapter": "V12",
    "section": "V12.5",
    "cwe": 552,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.5.2",
    "chapter": "V12",
    "section": "V12.5",
    "cwe": 434,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V12.6.1",
    "chapter": "V12",
    "section": "V12.6",
    "cwe": 918,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V13.1.1",
    "chapter": "V13",
    "section": "V13.1",
    "cwe": 116,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V13.1.2",
    "chapter": "V13",
    "section": "V13.1",
    "cwe": null,
    "l1": false,
    "l2": false,
    "l3": false
  },
  {
    "id": "V13.1.3",
    "chapter": "V13",
    "section": "V13.1",
    "cwe": 598,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V13.1.4",
    "chapter": "V13",
    "section": "V13.1",
    "cwe": 285,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V13.1.5",
    "chapter": "V13",
    "section": "V13.1",
    "cwe": 434,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V13.2.1",
    "chapter": "V13",
    "section": "V13.2",
    "cwe": 650,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V13.2.2",
    "chapter": "V13",
    "section": "V13.2",
    "cwe": 20,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V13.2.3",
    "chapter": "V13",
    "section": "V13.2",
    "cwe": 352,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V13.2.4",
    "chapter": "V13",
    "section": "V13.2",
    "cwe": null,
    "l1": false,
    "l2": false,
    "l3": false
  },
  {
    "id": "V13.2.5",
    "chapter": "V13",
    "section": "V13.2",
    "cwe": 436,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V13.2.6",
    "chapter": "V13",
    "section": "V13.2",
    "cwe": 345,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V13.3.1",
    "chapter": "V13",
    "section": "V13.3",
    "cwe": 20,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V13.3.2",
    "chapter": "V13",
    "section": "V13.3",
    "cwe": 345,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V13.4.1",
    "chapter": "V13",
    "section": "V13.4",
    "cwe": 770,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V13.4.2",
    "chapter": "V13",
    "section": "V13.4",
    "cwe": 285,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.1.1",
    "chapter": "V14",
    "section": "V14.1",
    "cwe": null,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.1.2",
    "chapter": "V14",
    "section": "V14.1",
    "cwe": 120,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.1.3",
    "chapter": "V14",
    "section": "V14.1",
    "cwe": 16,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.1.4",
    "chapter": "V14",
    "section": "V14.1",
    "cwe": null,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.1.5",
    "chapter": "V14",
    "section": "V14.1",
    "cwe": null,
    "l1": false,
    "l2": false,
    "l3": true
  },
  {
    "id": "V14.2.1",
    "chapter": "V14",
    "section": "V14.2",
    "cwe": 1026,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.2.2",
    "chapter": "V14",
    "section": "V14.2",
    "cwe": 1002,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.2.3",
    "chapter": "V14",
    "section": "V14.2",
    "cwe": 829,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.2.4",
    "chapter": "V14",
    "section": "V14.2",
    "cwe": 829,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.2.5",
    "chapter": "V14",
    "section": "V14.2",
    "cwe": null,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.2.6",
    "chapter": "V14",
    "section": "V14.2",
    "cwe": 265,
    "l1": false,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.3.1",
    "chapter": "V14",
    "section": "V14.3",
    "cwe": null,
    "l1": false,
    "l2": false,
    "l3": false
  },
  {
    "id": "V14.3.2",
    "chapter": "V14",
    "section": "V14.3",
    "cwe": 497,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.3.3",
    "chapter": "V14",
    "section": "V14.3",
    "cwe": 200,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.4.1",
    "chapter": "V14",
    "section": "V14.4",
    "cwe": 173,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.4.2",
    "chapter": "V14",
    "section": "V14.4",
    "cwe": 116,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.4.3",
    "chapter": "V14",
    "section": "V14.4",
    "cwe": 1021,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.4.4",
    "chapter": "V14",
    "section": "V14.4",
    "cwe": 116,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.4.5",
    "chapter": "V14",
    "section": "V14.4",
    "cwe": 523,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.4.6",
    "chapter": "V14",
    "section": "V14.4",
    "cwe": 116,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.4.7",
    "chapter": "V14",
    "section": "V14.4",
    "cwe": 1021,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.5.1",
    "chapter": "V14",
    "section": "V14.5",
    "cwe": 749,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.5.2",
    "chapter": "V14",
    "section": "V14.5",
    "cwe": 346,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.5.3",
    "chapter": "V14",
    "section": "V14.5",
    "cwe": 346,
    "l1": true,
    "l2": true,
    "l3": true
  },
  {
    "id": "V14.5.4",
    "chapter": "V14",
    "section": "V14.5",
    "cwe": 306,
    "l1": false,
    "l2": true,
    "l3": true
  }
];

/** Engine finding type to the requirements it bears on. */
export const FINDING_MAPPING: Record<string, FindingMapping> = {
  "command_injection": {
    "requirements": [
      "V5.3.8"
    ],
    "why": "the only requirement whose text names OS command injection (\"operating system\")"
  },
  "rce": {
    "requirements": [
      "V5.2.5",
      "V5.2.8"
    ],
    "why": "requirements whose text names template injection; the scanner tests ${7*7} evaluation"
  },
  "ssrf": {
    "requirements": [
      "V5.2.6"
    ],
    "why": "the requirement whose text names SSRF"
  },
  "directory_traversal": {
    "requirements": [
      "V5.3.9",
      "V12.3.1"
    ],
    "why": "requirements naming Local File Inclusion and path traversal"
  },
  "open_redirect": {
    "requirements": [
      "V5.1.5"
    ],
    "why": "the requirement whose text names URL redirects and forwards"
  },
  "json_injection": {
    "requirements": [
      "V5.3.6",
      "V13.2.2"
    ],
    "why": "requirements naming JSON injection and JSON schema validation"
  },
  "header_injection": {
    "requirements": [
      "V5.1.1",
      "V13.1.1"
    ],
    "why": "parameter pollution and consistent parsing; the scanner injects CRLF and payloads into request headers"
  },
  "auth_bruteforce": {
    "requirements": [
      "V2.2.1"
    ],
    "why": "the requirement whose text names brute force and anti-automation of credential testing"
  },
  "rate_limit_missing": {
    "requirements": [
      "V11.1.4"
    ],
    "why": "the requirement naming anti-automation controls against excessive calls"
  },
  "api_fuzz": {
    "requirements": [
      "V14.3.2"
    ],
    "why": "the requirement naming debug modes disabled in production; the scanner flags stack traces and 5xx"
  },
  "ssl_error": {
    "requirements": [
      "V9.1.1",
      "V9.2.1"
    ],
    "why": "requirements naming TLS for all client connectivity and trusted TLS certificates"
  },
  "subdomain": {
    "requirements": [
      "V10.3.3"
    ],
    "why": "the requirement naming subdomain takeover"
  }
};

/** `missing_security_header` carries the header name; each header is its own control. */
export const HEADER_MAPPING: Record<string, FindingMapping> = {
  "Content-Security-Policy": {
    "requirements": [
      "V14.4.3"
    ],
    "why": "the requirement naming a Content Security Policy response header"
  },
  "X-Frame-Options": {
    "requirements": [
      "V14.4.7"
    ],
    "why": "the requirement that content cannot be embedded in a third-party site by default"
  },
  "X-Content-Type-Options": {
    "requirements": [
      "V14.4.4"
    ],
    "why": "the requirement naming X-Content-Type-Options: nosniff"
  },
  "Referrer-Policy": {
    "requirements": [
      "V14.4.6"
    ],
    "why": "the requirement naming a suitable Referrer-Policy header"
  },
  "Strict-Transport-Security": {
    "requirements": [
      "V9.1.1"
    ],
    "why": "ASVS 4.0.3 names no HSTS requirement; V9.1.1 requires TLS with no fallback to unencrypted, which is what HSTS enforces",
    "approximate": true
  }
};

/**
 * Which scanner produces which finding type, from the engine's own registry.
 * Without this the product cannot tell a requirement that was tested and
 * passed from one nothing ever looked at.
 */
export const SCANNER_FINDINGS: Record<string, string[]> = {
  "api_fuzz": [
    "api_fuzz"
  ],
  "basic_scanner": [
    "basic_info",
    "ssl_error"
  ],
  "bruteforce": [
    "auth_bruteforce"
  ],
  "command_injection": [
    "command_injection"
  ],
  "directory_traversal": [
    "directory_traversal"
  ],
  "endpoint_discovery": [
    "endpoint_exposed"
  ],
  "header_injection": [
    "header_injection"
  ],
  "header_scanner": [
    "missing_security_header"
  ],
  "json_injection": [
    "json_injection"
  ],
  "open_redirect": [
    "open_redirect"
  ],
  "port_scanner": [
    "open_port"
  ],
  "prompt_injection": [
    "prompt_injection"
  ],
  "rate_limit_tester": [
    "rate_limit_missing"
  ],
  "rce": [
    "rce"
  ],
  "ssrf": [
    "ssrf"
  ],
  "subdomain_scanner": [
    "subdomain"
  ],
  "waf_detector": [
    "waf_detected"
  ]
};

/** Finding types with no requirement behind them, and why. Shown, not hidden. */
export const UNMAPPED_FINDINGS: Record<string, string> = {
  "prompt_injection": "ASVS 4.0.3 contains no requirement about LLM prompt injection. The standard predates it.",
  "basic_info": "reconnaissance output, not a control failure",
  "open_port": "an observation about the host, not an application control",
  "waf_detected": "an observation about the deployment, not a control failure",
  "endpoint_exposed": "a discovered path; whether it should be reachable is a question for a person",
  "error": "the engine reporting its own trouble, not a finding about the target",
  "timeout": "the engine reporting its own trouble, not a finding about the target"
};
